version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: lein deps
      - run: lein pom

      - save_cache:
          paths:
            - ~/.m2
            - .
          key: latest

      - run: lein test
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout

      - restore_cache:
          keys:
          - latest

      - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
          requires:
            - build
