name: Release

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: DeLaGuardo/setup-clojure@2.0
        run: lein release
